// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gRPC.Server.Data;

#nullable disable

namespace gRPC.Server.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("gRPC.Protos.Customer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = "12345678",
                            Address = "1234 Elm Street, Springfield, IL 62704, USA",
                            Age = 30,
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = "87654321",
                            Address = "5678 Oak Street, Springfield, IL 62704, USA",
                            Age = 25,
                            Name = "Jane Smith"
                        },
                        new
                        {
                            Id = "11223344",
                            Address = "9101 Maple Avenue, Springfield, IL 62704, USA",
                            Age = 40,
                            Name = "Alice Johnson"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
